apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
    spec:
      containers:
      - name: voting-app
        image: anshu049/voting-app
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
spec:
  selector:
    name: voting-app-pod
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
